name: Test
on: push

env:
  TEST_VAR: test
  TEST_IMAGE: ubuntu-latest

jobs:
  user-defined-variable:
    name: User defined variable
    runs-on: ${{ env.TEST_IMAGE }}
    steps:
      - name: Hello World
        run: echo 'Hello World'
      - name: Hello TEST
        run: echo "Hello ${TEST_VAR}"
