name: Test
on: push

env:
  TEST_VAR: test

jobs:
  user-defined-variable:
    name: User defined variable
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo 'Hello World'
      - name: Hello TEST
        run: echo "Hello ${TEST_VAR}"
